figure(1);
subplot(4,2,1);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,2);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,3);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,4);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,5);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,6);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,7);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
subplot(4,2,8);
imagesc(bar(edges,freq), xlabel('Area (\mum^2'), ylabel(['Counts' num2str(tc)]));
