%CLUSTER_DATA_SCRIPT Script to interface with MATLAB Bioinformatics Toolbox
% CLUSTERGRAM function.

data2cluster = aligned_area_norm(sortedID(1:200),:);
% secondaryData = ar_ac;

%% Get rid of unwanted rows
% [data2cluster,ind] = delete_nan_rows(data2cluster,1);
% deletedInd = setdiff(1:num_cells,foo);
% data2cluster(:,deletedInd) = [];
% % secondaryData(:,deletedInd) = [];

%% Cluster via hierarchical
cg = clustergram(data2cluster,'ImputeFun',@knnimpute,'linkage','average', ...
    'Cluster',1,'RowPDist','euclidean','Colormap',redbluecmap, ...
    'Dendrogram',5);

%% 

foo = cg.RowLabels;
for i = 1:numel(foo)
    ind(i) = str2num(foo{i});
end

% Plot clustered data

figure,pcolor(data2cluster(ind,:)),colorbar
figure,pcolor(secondaryData(ind,:)),colorbar
figure,errorbar(nanmean(data2cluster),nanstd(data2cluster))
figure,errorbar(nanmean(secondaryData),nanstd(secondaryData))

%%

distances = pdist(data2cluster,@nan_pearsoncorr);
% distances = pdist(data2cluster,@nan_eucdist);
Z = linkage(distances,'complete');
labels = cluster(Z,'maxclust',3);

[X,Y] = meshgrid(-10:10,1:num_peaks);

figure

showsub_vert(...
    @pcolor,{X(1:numel(labels(labels==1)),:),Y(1:numel(labels(labels==1)),:),data2cluster(labels==1,:)},...
    '1','shading flat;caxis([-20 20]);colorbar',...
    @plot,{-10:10,data2cluster(labels==1,:)},'','',...
    @errorbar,{-10:10,nanmean(data2cluster(labels==1,:)),nanstd(data2cluster(labels==1,:),[])},'','xlabel(''Aligned time'')',...
    @pcolor,{X(1:numel(labels(labels==2)),:),Y(1:numel(labels(labels==2)),:),data2cluster(labels==2,:)},...
    '2','shading flat;caxis([-20 20]);colorbar',...
    @plot,{-10:10,data2cluster(labels==2,:)},'','',...
    @errorbar,{-10:10,nanmean(data2cluster(labels==2,:)),nanstd(data2cluster(labels==2,:),[])},'','xlabel(''Aligned time'')',...
    @pcolor,{X(1:numel(labels(labels==3)),:),Y(1:numel(labels(labels==3)),:),data2cluster(labels==3,:)},...
    '3','shading flat;caxis([-20 20]);colorbar',...
    @plot,{-10:10,data2cluster(labels==3,:)},'','',...
    @errorbar,{-10:10,nanmean(data2cluster(labels==3,:)),nanstd(data2cluster(labels==3,:),[])},'','xlabel(''Aligned time'')',...
    3);

%%
figure
showsub_vert(...
    @pcolor,{X(1:numel(labels(labels==1)),:),Y(1:numel(labels(labels==1)),:),[pulse(labels==1).curve_padded]'},...
    '1','shading flat;colorbar;caxis([0 5e4]);',...
    @pcolor,{X(1:numel(labels(labels==2)),:),Y(1:numel(labels(labels==2)),:),[pulse(labels==2).curve_padded]'},...
    '2','shading flat;colorbar;caxis([0 5e4]);',...
    @pcolor,{X(1:numel(labels(labels==3)),:),Y(1:numel(labels(labels==3)),:),[pulse(labels==3).curve_padded]'},...
    '3','shading flat;colorbar;',...
    3);

% @pcolor,{data2cluster(labels==4,:)},'4','shading flat;caxis([-20 20]);colorbar',...
%     @errorbar,{-10:10,nanmean(data2cluster(labels==4,:)),nanstd(data2cluster(labels==4,:),[])},'','xlabel(''Aligned time'')',...
%     @pcolor,{data2cluster(labels==5,:)},'5','shading flat;caxis([-20 20]);colorbar',...
%     @errorbar,{-10:10,nanmean(data2cluster(labels==5,:)),nanstd(data2cluster(labels==5,:),[])},'','xlabel(''Aligned time'')',...
%     3);
